---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: General Config
- type: document
  path: src/data/general/menu.json
  label: Menu Links
- type: document
  path: package.json
  label: Site Info
- type: heading
  label: Footer Info
- type: document
  path: src/data/general/footer.json
  label: Social Media Footer
- type: heading
  label: Front Page (Home)
- type: document
  path: src/data/homepages/home.json
  label: Home
- type: heading
  label: Pages
- type: document
  path: src/data/inner-pages/about-us-page.json
  label: About Us
  match: "**/*"
- type: document
  path: src/data/inner-pages/matchpage.json
  label: Upcoming Matches
  match: "**/*"
- type: document
  path: src/data/inner-pages/faq.json
  label: FAQ's
  match: "**/*"
- type: document
  path: src/data/inner-pages/contact-us-page.json
  label: Contact
  match: "**/*"
- type: directory
  path: src/data/inner-pages
  label: Pages
  create: documents
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: src/data/blog-post
  label: Post
  create: documents
  match: "**/*"
  templates:
  - post-1
- type: directory
  path: src/data/games
  label: Games
  create: documents
  match: "**/*"
  templates:
  - games
upload_dir: uploads
public_path: src/data/images/**/*
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
